apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-pong
  template:
    metadata:
      labels:
        app: log-pong
    spec:
      containers:
        - name: log-output-app
          image: log-output:v5  # local image
          imagePullPolicy: Never
          env:
            - name: PING_PORT   # source host port
              value: "3001"
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-pong-config
                  key: MESSAGE
            - name: INFO_FILE
              value: /usr/share/app/config/information.txt
          volumeMounts:
            - name: config-vol
              mountPath: /usr/share/app/config
              readOnly: true
        - name: ping-pong-app
          image: ping-pong:latest
          imagePullPolicy: Never
          env:
            - name: PING_PORT   # app port
              value: "3001"
            # Point to Headless Service name
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            # Map the Secret keys
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: dbname
      volumes:
        - name: config-vol
          configMap:
            name: log-pong-config
