apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  # Since Backend Service is on port 80, we don't need to specify
  # :port
  BACKEND_PORT: "3000"
  FRONTEND_PORT: "3001"
