apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app # This MUST match the Service selector
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-app
          image: todo-app:v4    # local image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 # Explicitly document the port
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: todo-app-vol
              mountPath: /usr/src/app/data
