apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app # Ensure this matches the 'labels' in your Deployment
  ports:
    - name: http
      protocol: TCP
      port: 80         # Internal cluster port
      targetPort: 3000 # The port your app runs on inside the container
      nodePort: 30080  # External access via http://<Node-IP>:30080
