apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-pong
  template:
    metadata:
      labels:
        app: log-pong
    spec:
      volumes:
        - name: shared-log-pong
          persistentVolumeClaim:
            claimName: log-pong-claim
      containers:
        - name: log-output
          image: log-output:v3  # local image
          imagePullPolicy: Never
          env:
            - name: INFILE
              value: "/usr/src/app/data/output.txt"
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-log-pong
              mountPath: /usr/src/app/data
        - name: ping-pong
          image: ping-pong:v2   # local image
          imagePullPolicy: Never
          env:
            - name: OUTFILE
              value: "/usr/src/app/data/output.txt"
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: shared-log-pong
              mountPath: /usr/src/app/data
