apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mooc-log-pong-ingress
spec:
  rules:
    - http:
        paths:
          - path: /log
            pathType: Prefix
            backend:
              service:
                name: log-pong-svc
                port:
                  number: 3000
          - path: /pingpong
            pathType: Prefix
            backend:
              service:
                name: log-pong-svc
                port:
                  number: 3001
